// disclaimer.js

function loadDisclaimer() {
    const content = `
        <div class="container">
            <h1 class="title">Disclaimer</h1>
            <div class="content">
                <p>
                    The Barrage and Canal Design Web Application is a tool intended to assist users in the preliminary design and analysis of hydraulic structures such as barrages and canals. The outputs generated by this application are based on the inputs provided by the user and are intended for informational purposes only. 
                </p>
                <p>
                    Users are advised to exercise discretion and consult with qualified engineers and professionals before making any design or operational decisions based on the results obtained from this application. The developers and contributors to this application do not accept any liability for errors, omissions, or consequences arising from the use of this tool.
                </p>
                <p>
                    By using this application, you acknowledge and agree that you bear full responsibility for any actions taken based on the information provided herein.
                </p>
            </div>
        </div>
    `;

    document.getElementById('main').innerHTML = content;
}
